name: qtc_reproduction_env_py_3.10
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip:
      - matplotlib==3.8.2
      - numpy==1.26.3
      - openpyxl==3.1.2
      - pandas==2.2.0
      - seaborn==0.13.
      - sdv==1.13.1
